### ISSUE TITLE
Dies if no layer can be detected

### ISSUE THREAD

**Issue by Traumflug** [triffid/gcodeview#10]
I've thrown one of my PCB milling files onto it and it dies without a window appearing:

```
$ ./gcodeview Gen7Board-production-back-030.cnc
Indexing lines... 0 layers OK
Scan: realloc layer failed: Success
```

While I'm not aware of a working G-code viewer for Linux and having one would be really useful for me, I'm not so keen on working on yet another RepRap related project, so no patch by me for now. I can email you the G-code, though.

**Comment by triffid** [comment]
I think I know why- the layering code uses E codes to identify hop/z-lift in order to not mark the hop as a new layer.

With no E codes and that code in place, it won't find any layers!

So, now I have to work out how to 1) sensibly deal with hop/z-lift and 2) gracefully decide when there aren't going to be any E codes and do something useful

**Comment by triffid** [comment]
let me know if latest master works better for you, close or update this bug if so :)

**Comment by Traumflug** [comment]
Triffid, you're the greatest! Works now flawlessly.

**Comment by triffid** [comment]
hope you enjoy the purple for "travel under current layer height" (milling) which most users may never see ;)

**Comment by Traumflug** [comment]
I do, and also the different color for rapid moves (G0), which might be an artefact of the rapid moves being above "layer height".

**Comment by triffid** [comment]
yes there's no distinction made between G0 and G1, but travels above layer height are coloured red. this is to support hop/z-lift for repraps, but is useful here too :)
