### ISSUE TITLE
Issues with "make" on debian jessie

### ISSUE THREAD

**Issue by bethebeer** [triffid/gcodeview#17]
Just upgraded to Jessie, was using Debian Wheezy, where gcodeview was working well. 
I used git clone, and then once in the directory the command "make" had this output:

cc main.o `pkg-config --libs sdl ftgl fontconfig  gl` -o gcodeview
/usr/bin/ld: main.o: undefined reference to symbol 'hypotf@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: **\* [gcodeview] Error 1

**Comment by triffid** [comment]
let me know if that fixes it :)

**Comment by bethebeer** [comment]
this is now the output:

cc main.o `pkg-config --libs sdl ftgl fontconfig  gl` -lm -o gcodeview
Building for [Linux].

when running in the command line with a gcode file, this is my output:
File is 6559902 long
Indexing lines...
found layer 0
FTGL createFont failed: No such file or directory

normally i run it just from double clicking a .gcode file, i set up an .xml file in a mime folder somewhere, and have set up a .desktop for the application.

**Comment by triffid** [comment]
wonderful, progress is occurring :) you now have a completely different and unrelated error!

for best results, close this issue and open a new one: "FTGL createFont failed: No such file or directory"

although I can tell you right now that it sounds like your OS is screwed up because the path passed to FTGL comes direct from fontconfig, and gcodeview has nothing to do with it- we simply pass it directly from one to the other without examining it at all.

See the block from https://github.com/triffid/gcodeview/blob/master/main.c#L1028 to L1044

If you find a way to massage that block into providing a valid path on your OS, please send a pull request!

**Comment by bethebeer** [comment]
thanks for the help.  i will open up an issue here and on debian's site. I'll post a reference of each one, to the other. It does look like it is an issue in Debian, though.
